query GetToolBySlug($slug: String!, $toolStatus: ToolStatus) {
  getToolBySlug(slug: $slug, toolStatus: $toolStatus) {
    data {
      id
      name
      description
      shortDescription
      slug
      handle
      thumbnailUrl
      ranking
      toolType
      visibility 
      toolStatus
      ownerId
      verifiedBySuperAdmin
      createdAt
      updatedAt
      deletedAt
      owner {
        id
        email
        fullName
        profilePicture
        userType
        isVerified 
        username

      }
      inputSchema {
        id
        schema
        toolId
        createdAt
        updatedAt
      }
      outputSchema {
        id
        schema
        toolId
        createdAt
        updatedAt
      }
      toolMetadata {
        id
        title
        description
        keywords
        ogTitle
        ogDescription
        ogImageUrl
        toolId
        createdAt
        updatedAt
      }
      comment {
        id
        comment
        createdAt
        updatedAt
      }
    }
    error {
      message
      code
      path
    }
  }
}