query SearchListedAiTools($input: SearchListedAiToolInput!) {
  searchListedAiTools(input: $input) {
    data {
      id
      name
      slug
      shortDescription
      logoUrl
      websiteUrl 
      
      videoUrl
      pricingType
      aiType 
      domains 
      modalities 
      
      toolUserTypes
      platforms
      integrationOptions
      popularityScore
      featured
      verified
      useCases
      createdAt
      updatedAt
    }
    error {
      message
      code
      path
    }
  }
}